import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f9",
        "on-primary-fixed": "#1c1b1b",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c7",
        primary: "#000000",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbf9f9",
        tertiary: "#000000",
        "surface-container-low": "#f5f3f3",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#474646",
        "surface-variant": "#e4e2e2",
        "on-background": "#1b1c1c",
        surface: "#fbf9f9",
        "surface-container-high": "#e9e8e7",
        "error-container": "#ffdad6",
        "secondary-container": "#dddddd",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-surface": "#1b1c1c",
        outline: "#747878",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "on-secondary-container": "#606161",
        "primary-container": "#1c1b1b",
        "surface-container": "#efeded",
        "on-surface-variant": "#444748",
        "tertiary-fixed": "#e2e2e2",
        secondary: "#5d5f5f",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#858383",
        "on-secondary-fixed-variant": "#454747",
        "inverse-surface": "#303031",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-highest": "#e4e2e2",
        "on-tertiary-container": "#838484",
        "on-error-container": "#93000a",
        "inverse-primary": "#c8c6c5",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary-fixed": "#1a1c1c",
        "surface-dim": "#dbdad9",
        "secondary-fixed": "#e2e2e2",
        "tertiary-container": "#1a1c1c",
        "outline-variant": "#c4c7c7",
        foreground: "var(--foreground)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "20px",
        gutter: "24px",
        "margin-desktop": "64px",
        "section-gap": "128px",
        unit: "8px",
      },
      fontFamily: {
        "body-lg": ["var(--font-hanken)"],
        "headline-lg": ["var(--font-eb-garamond)"],
        "headline-md": ["var(--font-eb-garamond)"],
        "label-sm": ["var(--font-hanken)"],
        "label-md": ["var(--font-hanken)"],
        "display-lg": ["var(--font-eb-garamond)"],
        "display-lg-mobile": ["var(--font-eb-garamond)"],
        "body-md": ["var(--font-hanken)"],
        sans: ["var(--font-hanken)"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
